apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pv-claim
  namespace: jira
  labels:
    app: jira
  annotations:
    "volume.beta.kubernetes.io/storage-class": "slow"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      name: jira-pv
