apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv 
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
  labels:
    name: jira-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 127.0.0.1
    path: /export/nfs/jira-pv
